### ISSUE TITLE
类似登录这种公用业务模块该怎么处理呢

### ISSUE THREAD

**Issue by TaitYoung** [BaronZ88/ModularizationProject#2]
我理解的loginModule应该是和NewHouseModule业务模块同级的。如果两者之间做到解耦，那在单独运行新房业务模块时，怎么使用登录模块的功能呢？ 望回复，谢谢。

**Comment by BaronZ88** [comment]
看你怎么理解了，我更倾向于将 Login 模块下放到业务组件层。毕竟登录用户信息是所有业务公用的，这样 NewHouseModule 就可以依赖 Login 。

**Comment by TaitYoung** [comment]
谢谢。现在就是这么做的。
依赖关系（单向）：NewHouseModule > login > commonBussiness

**Comment by BaronZ88** [comment]
不客气
