### ISSUE TITLE
Fragment 如何模块化?

### ISSUE THREAD

**Issue by LoveqLRC** [BaronZ88/ModularizationProject#3]
例如微信那样的布局，4`Tab`的都是`fragment`填充，如何组件化?我看了一些组件化的文章都是以`Activity`为单位进行，而实际开发中往往是一个`Activity`带几个`Fragment`。

**Comment by BaronZ88** [comment]
如果是公用的 Fragment 可以下放到业务逻辑层；对于类似微信这总非公用 Fragment，我们现在是通过反射来实现的。

**Comment by MrJiao** [comment]
https://github.com/alibaba/ARouter 支持路由获取Fragment

**Comment by LoveqLRC** [comment]
3q
